export const currencyList = [
  { label: 'AUD', name: 'Australian Dollar', symbol: '$' },
  { label: 'BGN', name: 'Bulgarian Lev', symbol: 'лв' },
  { label: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
  { label: 'CAD', name: 'Canadian Dollar', symbol: '$' },
  { label: 'CHF', name: 'Swiss Franc', symbol: 'CHF' },
  { label: 'CNY', name: 'Chinese Renminbi Yuan', symbol: '¥' },
  { label: 'CZK', name: 'Czech Koruna', symbol: 'Kč' },
  { label: 'DKK', name: 'Danish Krone', symbol: 'kr' },
  { label: 'EUR', name: 'Euro', symbol: '€' },
  { label: 'GBP', name: 'British Pound', symbol: '£' },
  { label: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$' },
  { label: 'HUF', name: 'Hungarian Forint', symbol: 'Ft' },
  { label: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp' },
  { label: 'ILS', name: 'Israeli New Sheqel', symbol: '₪' },
  { label: 'INR', name: 'Indian Rupee', symbol: '₹' },
  { label: 'ISK', name: 'Icelandic Króna', symbol: 'kr' },
  { label: 'JPY', name: 'Japanese Yen', symbol: '¥' },
  { label: 'KRW', name: 'South Korean Won', symbol: '₩' },
  { label: 'MXN', name: 'Mexican Peso', symbol: '$' },
  { label: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM' },
  { label: 'NOK', name: 'Norwegian Krone', symbol: 'kr' },
  { label: 'NZD', name: 'New Zealand Dollar', symbol: '$' },
  { label: 'PHP', name: 'Philippine Peso', symbol: '₱' },
  { label: 'PLN', name: 'Polish Złoty', symbol: 'zł' },
  { label: 'RON', name: 'Romanian Leu', symbol: 'lei' },
  { label: 'SEK', name: 'Swedish Krona', symbol: 'kr' },
  { label: 'SGD', name: 'Singapore Dollar', symbol: '$' },
  { label: 'TRY', name: 'Turkish Lira', symbol: '₺' },
  { label: 'USD', name: 'United States Dollar', symbol: '$' },
  { label: 'ZAR', name: 'South African Rand', symbol: 'R' },
]
